apiVersion: v1
kind: Service
metadata:
  name: bookings-service
type: ClusterIP
spec:
  selector:
    app: bookings
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-deployment
spec:
  selector:
    matchLabels:
      app: bookings
  replicas: 2
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: 637423360833.dkr.ecr.us-east-1.amazonaws.com/waqqly-bookings:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "mongodb://db/Booking"
            - name: JWT_SECRET
              value: "walker_booking"
            - name: NODE_ENV
              value: "development"
            - name: APP_URI
              value: "http://gateway-service:3000"
