apiVersion: v1
kind: Service
metadata:
  name: walkers-service
spec:
  selector:
    app: walkers
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: walkers-deployment
spec:
  selector:
    matchLabels:
      app: walkers
  replicas: 2
  template:
    metadata:
      labels:
        app: walkers
    spec:
      containers:
        - name: walkers
          image: 637423360833.dkr.ecr.us-east-1.amazonaws.com/waqqly-walkers:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "mongodb://db/Walker"
            - name: JWT_SECRET
              value: "walker_booking"
            - name: NODE_ENV
              value: "development"
            - name: APP_URI
              value: "http://gateway-service:3000"
